### ISSUE TITLE
http: TLS handshake error from <IP>:<PORT>: remote error: tls: bad certificate

### ISSUE THREAD

**Issue by divyangjp** [aws-samples/aws-secret-sidecar-injector#46] opened 2021-03-18 11:00 UTC
I installed helm chart for aws-secret-sidecar-injector following the guide at https://aws.amazon.com/blogs/containers/aws-secrets-controller-poc/

A new deployment with proper annotations is created. 
AWS iam_role and policies are properly created.
Kubernetes `serviceaccount` is created in line with the guide and specified in the deployment `spec`
But the deployment pod doesn't have secret mounted at `/tmp` directory
When checking logs for pod `secret-inject-xxxx-xxx`, it has the error as described in title

```
2021/03/18 10:03:05 http: TLS handshake error from 10.0.20.176:53728: remote error: tls: bad certificate
2021/03/18 10:03:05 http: TLS handshake error from 10.0.20.176:53734: remote error: tls: bad certificate
2021/03/18 10:44:40 http: TLS handshake error from 10.0.20.176:38152: remote error: tls: bad certificate
2021/03/18 10:46:43 http: TLS handshake error from 10.0.10.126:59140: remote error: tls: bad certificate
2021/03/18 10:49:39 http: TLS handshake error from 10.0.10.126:60042: remote error: tls: bad certificate
```

**Comment by amit0701** [comment] 2021-03-18 12:28
Hi @divyangjp , What is the version of Kubernetes cluster ? This is recently fixed in #43 . Did you also try using an updated Helm chart ? helm repo update

**Comment by divyangjp** [comment] 2021-03-20 10:08
@amit0701 I was installing the helm chart in `kube-system` which gave the error. When I installed it in `default` namespace, the error disappeared and pod could access secret value.

**Comment by turbotankist** [comment] 2021-04-06 13:17
The problem is in
_helpers.tpl
it should be
```
{{- $cert := genSignedCert (printf "secret-inject.%s.svc" .Release.Namespace) nil (list "secret-inject.default.svc" (printf "secret-inject.%s.svc" .Release.Namespace))  3650 $ca -}}
```

cause if alternate DNS  is exist then CN isn't used
So cert valid only for secret-inject.default.svc
and deployment works only in default namespace

And with my fix we get
```
  X509v3 Subject Alternative Name: 
                DNS:secret-inject.default.svc, DNS:secret-inject.kube-system.svc
```
and all is working

**Comment by amit0701** [comment] 2021-04-19 12:37
LGTM

**Closed** 2021-04-20 22:39 UTC
